# How is this different from keys.py?#
space: key(space)
enter: key(enter)
tab: key(tab)
dot: key(dot)
questo: insert("?")
tilde: insert("~")
bang: insert("!")
dollar: insert("$")
crunder: insert("_")
paren: insert("(")
are paren: insert(")")
less than sign: insert("<")
greater than sign: insert(">")
star: insert("*")
pound: insert("#")
percy: insert("%")
caret: insert("^")
loco: insert("@")
spike: insert("|")
double quote: insert('"')
plus sign: insert("+")
